### ISSUE TITLE
updateInternalSymbol shouldn't clear the bundle

### ISSUE THREAD

**Issue by ramagottfried** [j-bresson/symbolist#7]
hey jean -- as you suspected, the problem we were seeing just before you left is due to updateInternalSymbol clearing the internal_symbol on update.

if possible, it'd be great to only update the changed data... not sure how to do that at the moment, but maybe you do?

**Comment by ramagottfried** [comment]
looks like the Juce OSC bundle is just a vector of addresses and values without any knowledge about whether an address exists already or not -- i.e. when you add a new address+value it calls .add() 

maybe we should use a hash table like [std::map](http://en.cppreference.com/w/cpp/container/map) or [std::unordered_map](http://en.cppreference.com/w/cpp/container/unordered_map) ?

**Comment by ramagottfried** [comment]
... I was thinking that a hash table might allow us to remove duplicate addresses, but I guess we could also make a copy and check for duplicate addresses each time we update the bundle (to make sure we use the most recent)...

basically I think we need a `union` to update values while keeping whatever other data might be in the bundle (displayed or not)

**Comment by j-bresson** [comment]
at the moment when a symbol needs to be updated / modified the OSC bundle is reinitialised and recreated. this can include additional data we might have stored somewhere else.
this is not optimal but it does what we need I think.

**Comment by ramagottfried** [comment]
ok sounds good
